export const LOGIN_FORM_ACTIVE = "LOGIN_FORM_ACTIVE";
export const REGISTER_FORM_ACTIVE = "REGISTER_FORM_ACTIVE";
export const USER_FORM_ACTIVE = "USER_FORM_ACTIVE";

export const SHOW_NEW = "SHOW_NEW";
export const SHOW_ALL = "SHOW_ALL";
export const SHOW_VIEWED = "SHOW_VIEWED";