export const LOAD_POSTS = "LOAD_POSTS";
export const ADD_POST = "ADD_ITEM";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const EDIT_POST = "EDIT_POST";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const LOGIN_FORM_CHANGE = "LOGIN_FORM_CHANGE";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";

export const GET_PROFILE = "GET_PROFILE";